---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/timgetz/spring-cloudconfig-wa-tolls
          search-paths:
            - 'station*'
          repos:
            perf:
              pattern:
                - '*/perf'
              uri: https://github.com/timgetz/spring-cloudconfig-wa-tolls-perf
              search-paths:
                - 'station*'
        encrypt:
          enabled: false
          #username: uname
          #password: pass
security:
  basic:
    enabled: true
  user:
    name: pluralsight
    password: pluralsight
